---
name: Redes e internet
locale: es
type: learning
beta: false
teacher_info: "Esta lección debería atacar, al menos, las siguientes dos cuestiones:
  \n\n- hay programas que se ejecutan en muchas computadoras\n- no todas las computadoras
  son obvias"
language: text
id_format: "%05d"
order:
- 1
- 2
- 3
- 14
- 4
- 5
- 6
- 7
- 15
- 8
- 9
- 10
