---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Porque todas las canciones son del viento
  checked: false
- value: Porque viene descargada en su computadora y Ale no lo sabe
  checked: false
- value: Porque Ale tiene acceso a Internet, y la música se transfirió desde la computadora
    de Espótifai hasta la suya
  checked: true
- value: No es posible, ¡un hechicero lo hizo!
  checked: false
name: Melomanía
