---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Es imposible
  checked: false
- value: Utilizando una red LAN
  checked: false
- value: Conectando redes LAN para crear una red que abarque un área más extensa
  checked: true
name: Local vs. Visitante
