---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: '4'
  checked: false
- value: '2'
  checked: true
- value: '1'
  checked: false
- value: Ninguna
  checked: false
name: Tejiendo una red
