---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Por paloma mensajera
  checked: false
- value: Por las raíces de los árboles, que son buenas conductoras de información
  checked: false
- value: Por el aire
  checked: true
name: Globalización y olvidate
